defaults:
  - benchmark
  - scenario: inference
  - backend: openvino
  - launcher: process
  - _base_
  - _self_

name: cpu_openvino_8bit_bert

backend:
  device: cpu
  reshape: true
  no_weights: true
  load_in_8bit: true
  model: google-bert/bert-base-uncased
  reshape_kwargs:
    batch_size: 1
    sequence_length: 128

scenario:
  memory: true
  latency: true

  input_shapes:
    batch_size: 1
    sequence_length: 128
