defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: ipex
  - _base_
  - _self_

name: cpu_ipex_bert

launcher:
  numactl: true
  numactl_kwargs:
    cpunodebind: 0
    membind: 0

backend:
  device: cpu
  no_weights: false # on multi-node machines, inline weights initialization harms performance
  torch_dtype: float32 # use bfloat16 on compatible Intel CPUs
  model: google-bert/bert-base-uncased

scenario:
  memory: true
  latency: true

  input_shapes:
    batch_size: 1
    sequence_length: 128
