defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

name: text_generation

launcher:
  device_isolation: False
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0, 1, 2, 3, 4, 5, 6, 7
  no_weights: False
  task: text-generation
  model: deepseek-ai/DeepSeek-R1
  torch_dtype: bfloat16
  device_map: auto

scenario:
  dataset_name: EnergyStarAI/text_generation
  text_column_name: text
  num_samples: 1000
  truncation: True
  iterations: 10

  input_shapes:
    batch_size: 1
