defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

name: text_classification

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  task: text-classification
  model: lvwerra/distilbert-imdb

scenario:
  dataset_name: EnergyStarAI/text_classification
  text_column_name: text
  num_samples: 1000
  truncation: True

  input_shapes:
    batch_size: 1
