name: Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install quality requirements
        run: |
          pip install uv
          uv pip install --upgrade pip
          uv pip install ruff
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Check style
        run: make quality
