name: Energy Star Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  UV_SYSTEM_PYTHON: 1
  UV_TORCH_BACKEND: auto

jobs:
  run_energy_star:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'energy_star')
      }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run energy star
        run: |
          make test-energy-star
