name: CLI CPU IPEX Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  UV_TORCH_BACKEND: cpu

permissions: {}

jobs:
  run_cli_cpu_ipex_tests:
    permissions:
      contents: read
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'cli') ||
      contains( github.event.pull_request.labels.*.name, 'cpu') ||
      contains( github.event.pull_request.labels.*.name, 'ipex') ||
      contains( github.event.pull_request.labels.*.name, 'cli_cpu_ipex')
      }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true

      - name: Run tests
        run: |
          make test-cli-cpu-ipex

      - name: Run examples
        run: |
          make test-cli-cpu-ipex-examples
